steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - sgtm_cloud_run_updater
  - --region=europe-west3
  - --source=.
  - --trigger-http
  - --gen2
  - --runtime=nodejs20
  - --entry-point=check_cloud_run
  
  # Remove the next comment for public access
  #- --allow-unauthenticated

#  - --service-account=cd-bigquery-to-firestore@artful-shelter-265814.iam.gserviceaccount.com
# Dont forget to set cloud build permissions in gcp cloud console settings